### PR TITLE
better ES translation + PT and ZH translation

### PR DESCRIPTION
**Pull request by pachadotdev**
PT and ZH was checked with help from native speakers :)

### CODE REVIEW

**Comment by rich-iannone** [comment]
This is phenomenal. Thank you * 1000 !

**Comment by rich-iannone** [comment]
There's an issue with the translation YAML in CI (examples failing) that I can help figure out later tonight (if you don't get to it first).

**Comment by rich-iannone** [comment]
I isolated it down to the `footer_text_fragment` YAML key. Something in there is not working.

**Comment by pachadotdev** [comment]
thanks Richard, I can resume this after my inference exam tomorrow, this was just a temporary break from study

**Comment by rich-iannone** [comment]
It's actually all good now! Just missing a few quotes. Is it okay if I merge?

**Comment by rich-iannone** [comment]
Oh never mind, there's a Windows problem :( Can't merge this yet.

**Comment by rich-iannone** [comment]
I have a solution for this problem (I think it’ll work!). More on this later.

**Comment by pachadotdev** [comment]
maybe the problem with Windows is that 。is different from .
in chinese 。is the dot character

**Comment by rich-iannone** [comment]
It was the Unicode characters in Chinese. That's okay though. I have a solution (pushed now, and tested in Windows 10, R 4.0.2) that transforms the Unicode to code points. A build script in `data-raw` called `00-reencode_text.R` takes the source YAML file (now also in `data-raw` as `translations_source.yml` and converts all the translation strings to the safe, compatible format. The transformed data is stored as an RDS file in `inst/text` as `translations_built`.

**Pull request merged**
