### PR TITLE
Roll-back tracking full language objects for internal calls

### LINKED ISSUE #567: File size increase in serialising interrogated agents
There seems to be some kind of regression in the dev version of {pointblank} that is causing interrogated agents that are saved to disk are over an order of magnitude larger than the ones produced by the version on CRAN.

I am using {pointblank} with {targets} and saving interrogated agents to disk using {qs}. I have a large validation pipeline, which I unfortunately cannot share, with creates a target on disk with size of ~14 MB. When using the dev version, this file size explodes to ~500 MB. In both cases I am ensuring `tbl_checked` is not extracted (either through the non-public API or the new argument in `interrogate()`).

Has there been anything added to the validation object which could account for the explosion in file size?

### PR DESCRIPTION
**Pull request by yjunechoe**
This is a small amendment of #543, which introduced a problem in serialization size due to `validation_set$capture_stack$pb_call` storing language objects with environments attached.

Now, we simply track the name of the internal function in string (ex: `"tbl_val_comparison"`) as opposed to the full call (ex: `tbl_val_comparison(...)`). No user-visible changes.

What used to be 13kB -> 208kB is now 1Kb -> 133b. Reprex from #567:

```r
# Setup
agent <- 
  create_agent(
    tbl = pointblank::small_table,
    tbl_name = "small_table",
    label = "`create_agent()` example.",
    actions = action_levels(
      warn_at = 0.10,
      stop_at = 0.25,
      notify_at = 0.35
    )
  )

agent <-
  agent %>% 
  col_exists(columns = c(date, date_time)) %>%
  col_vals_regex(
    columns = b,
    regex = "[0-9]-[a-z]{3}-[0-9]{3}"
  ) %>%
  rows_distinct() %>%
  col_vals_gt(columns = d, value = 100) %>%
  col_vals_lte(columns = c, value = 5) %>%
  col_vals_between(
    columns = c,
    left = vars(a), right = vars(d),
    na_pass = TRUE
  ) %>%
  interrogate()
  
  
# In memory
pb_call <- lapply(agent$validation_set$capture_stack, `[[`, "pb_call")
scales::label_bytes()(
  as.integer(object.size(pb_call))
)
#> [1] "1 kB"

# Serialized
f <- tempfile()
saveRDS(pb_call, f)
scales::label_bytes()(
  file.size(f)
)
#> [1] "133 B"

# Equivalence
identical(pb_call, readRDS(f))
#> [1] TRUE

pb_call
#> [[1]]
#> [1] "tbl_col_exists"
#> 
#> [[2]]
#> [1] "tbl_col_exists"
#> 
#> [[3]]
#> [1] "tbl_val_regex"
#> 
#> [[4]]
#> [1] "tbl_rows_distinct"
#> 
#> [[5]]
#> [1] "tbl_val_comparison"
#> 
#> [[6]]
#> [1] "tbl_val_comparison"
#> 
#> [[7]]
#> [1] "tbl_vals_between"
```

Rider: fixes a typo in examples of `?create_agent`

### CODE REVIEW

**Comment by yjunechoe** [comment]
@rich-iannone I think this fixes the original issue and should be ready to go!

One Q for this PR while I'm on it - do we need a test for memory size at serialization? I suppose it'd only exist to guard against regressions like this, but could be useful since it can easily go unnoticed - though I'm unsure how it's best implemented (some upper bound size?) or whether it's stable enough to be useful as a test at all (across OS, R setups, etc.).

**Comment by rich-iannone** [comment]
> @rich-iannone I think this fixes the original issue and should be ready to go!

This is amazing!! Thank you so much for working with the user to track this down (and of course for the PR).

> One Q for this PR while I'm on it - do we need a test for memory size at serialization? I suppose it'd only exist to guard against regressions like this, but could be useful since it can easily go unnoticed - though I'm unsure how it's best implemented (some upper bound size?) or whether it's stable enough to be useful as a test at all (across OS, R setups, etc.).

This seems somewhat brittle as a test. There might be a convenient way to monitor the size of serialized agents through a separate workflow that just reports the sizes as an artifact (which we could check every now and then).

**Comment by yjunechoe** [comment]
> This seems somewhat brittle as a test. There might be a convenient way to monitor the size of serialized agents through a separate workflow that just reports the sizes as an artifact (which we could check every now and then).

Thanks - this makes sense! For now I just added a manual test `manual_tests/tests_agent_serialization_size.R` that at least checks for the worst-case scenario of the entire user environment being snapshotted and written out as part of the agent, when using `saveRDS()`.

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Comment by rich-iannone** [comment]
Thanks again!

**Pull request merged**
