### PR TITLE
Resolve validation step info to string for hashing

### LINKED ISSUE #509: Validation steps sometimes do not align in the multiagent
## Problem

In the multiagent, we expect validation steps to align when they are equivalent in form (i.e., identical function calls). For example, four agents below all share the `col_vals_not_null(c)` step and the hash for this step is shared, regardless of when/where the step is added to the agent:

```r
library(pointblank)
agent <- create_agent(small_table)

agent_global1 <- agent %>% 
  col_vals_not_null(c) %>% 
  interrogate()
agent_global2 <- agent %>% 
  col_vals_not_null(c) %>% 
  interrogate()
agent_local1 <- local({
  agent %>% 
    col_vals_not_null(c) %>% 
    interrogate()
})
agent_local2 <- local({
  agent %>% 
    col_vals_not_null(c) %>% 
    interrogate()
})
create_multiagent(agent_global1, agent_global2, agent_local1, agent_local2) %>% 
  get_multiagent_report(display_mode = "wide")
```

image

However, the same step defined in different environments fail to align when they involve special data structures that record the environment. This is the case for:
1) Functions passed to `preconditions`, when the function is defined inline (e.g., using the magrittr syntax `. %>% ...`)

```r
agent_local_precondition <- local({
  small_table %>% 
    create_agent() %>% 
    col_vals_not_null(c, preconditions = . %>% identity()) %>% 
    interrogate()
})
agent_global_precondition <- small_table %>% 
  create_agent() %>% 
  col_vals_not_null(c, preconditions = . %>% identity()) %>% 
  interrogate()
create_multiagent(agent_local_precondition, agent_global_precondition) %>% 
  get_multiagent_report(display_mode = "wide")
```

image

- Quosures (i.e., `vars()`) passed to `values`

```r
agent_local_vars <- local({
  small_table %>% 
    create_agent() %>% 
    col_vals_gt(c, value = vars(a)) %>% 
    interrogate()
})
agent_global_vars <- small_table %>% 
  create_agent() %>% 
  col_vals_gt(c, value = vars(a)) %>% 
  interrogate()
create_multiagent(agent_local_vars, agent_global_vars) %>% 
  get_multiagent_report(display_mode = "wide")
```

image

This raises two concerns:
1. Hashing can be overly strict, in ways that may be unpredictable for the user (especially in real world scenarios where agents are defined months or years apart in different workspaces and setups).
2. Hashing the environment can cause severe performance problems when large objects are involved (#508)

## Possible remedy

1. Resolve such complex data structures to string before they're passed to `digest::sha1()`, to avoid hashing the environment
2. Build in a (opt-in or fallback) mechanism for backwards compatibility to account for (1), such as by having the multiagent re-generate the hash for every step for the purposes of alignment

### PR DESCRIPTION
**Pull request by yjunechoe**
# Summary

This PR introduces a new internal function `hash_validation_step()` which ensures that functions (in `preconditions`) and quosures (`vars()` in `value`/`left`/`right`) are resolved to character for the purposes of hashing. In turn, `digest::sha1()` is guaranteed to always receive a character vector - this resolves issues with environment hashing as described in #509.

Currently, the new hashing implementation *replaces* the previous one (vs. being opt-in).

# Pending

- Backwards compatibility for older agents in the multiagent: we would need to re-hash agents' steps for the purposes of alignment.

- More tests to check that this new method does not create false positives in step alignments. Alignment should respect identity up to yaml-equivalence.

### CODE REVIEW

**Comment by yjunechoe** [comment]
Also `dplyr::storms` turns out to be one of those data that get regularly updated. Since updates to dplyr can make snaps outdated (therefore causing tests to fail unexpectedly), I've commented that out in the draft_validation tests (so the PR will also resolve the testthat GHA failing on main).

**Comment by yjunechoe** [comment]
I think this should do the trick!

Some notes on the implementation:

- Hashing logic is factored out into `hash_validation_step()`, which resolves everything to string before `digest::sha1()` is called. Current implementation appends `"-v0.12"` to the hash. 
- An agent's steps can be re-hashed via another new internal function `rehash_agent()`, which iterates the above function over the rows of the agent's `$validation_set`. This returns an identical agent that only changes in `$validation_set$sha1`. It can be used in isolation to repair or update an agent's hash for validation steps:

```r
agent1 <- create_agent(small_table) %>%
  rows_distinct() %>% 
  interrogate()
agent1$validation_set$sha1
#> [1] "adac947b3a26f7df4bfd374b5fff4e67b4190f8b-v0.12"
agent1$validation_set$sha1 <- "bad hash"
agent2 <- rehash_agent(agent1)
agent2$validation_set$sha1
#> [1] "adac947b3a26f7df4bfd374b5fff4e67b4190f8b-v0.12"
```

- `create_multiagent()` now rehashes all agents it receives, if it detects any bad or conflicting hash versions. Currently, it's either that all hash are v0.12 (doesn't trigger rehashing) or not (triggers rehash). We could expose an argument to let the user control the rehashing method, but maybe not necessary to introduce that at this stage (we only have 2 options and one is clearly better).

```r
agent1$validation_set$sha1
#> [1] "bad hash"
agent2$validation_set$sha1
#> [1] "adac947b3a26f7df4bfd374b5fff4e67b4190f8b-v0.12"
multiagent <- create_multiagent(agent1, agent2)
multiagent$agents[[1]]$validation_set$sha1
#> [1] "adac947b3a26f7df4bfd374b5fff4e67b4190f8b-v0.12"
multiagent$agents[[2]]$validation_set$sha1
#> [1] "adac947b3a26f7df4bfd374b5fff4e67b4190f8b-v0.12"

get_multiagent_report(multiagent, display_mode = "wide")
```

image

---

All in all, this fixes both the alignment issue (#509) and the performance issue (#508). There are no user visible changes beyond "bugfix in multiagent alignment", so the news item for this PR just reports that.

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Comment by rich-iannone** [comment]
This is really great work! Feel free to merge any time.

**Pull request merged**
