### PR TITLE
update dev version install instructions

### PR DESCRIPTION
**Pull request by luisDVA**
# Summary

updated instructions to install from GitHub using pak

# Related GitHub Issues and PRs

- Ref: none

# Checklist

- [x ] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html).
- [ N/A] I have listed any major changes in the [NEWS](https://github.com/rstudio/pointblank/blob/main/NEWS.md).
- [ N/A] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/rstudio/pointblank/tree/main/tests/testthat) for any new functionality.

### CODE REVIEW

**Comment by pachadotdev** [comment]
hi @luisDVA 
what's the problem with remotes? I tried now and it works

**Comment by luisDVA** [comment]
hi!
current instructions mention **devtools** rather than remotes (which is more lightweight) and my PR updated the instructions to use pak, which is the current practice in repos across the Rstudio and tidyverse organizations . please close or edit if I stepped out of line w/ this

**Comment by pachadotdev** [comment]
> hi! current instructions mention **devtools** rather than remotes (which is more lightweight) and my PR updated the instructions to use pak, which is the current practice in repos across the Rstudio and tidyverse organizations . please close or edit if I stepped out of line w/ this

good point!!

I will edit this

desktop users should be ok with `remotes`

I shall add a note to use `pak` when using this in a cluster or gh-actions pipelines

**Review by rich-iannone — APPROVED** [review]
Thanks!

**Pull request merged**
