### PR TITLE
Add danish lang

### PR DESCRIPTION
**Pull request by LDalby**
# Summary

Thank you for contributing to **pointblank**! To make this process easier for everyone, please explain the context and purpose of your contribution. Also, list the changes made to the existing code or documentation.

# Related GitHub Issues and PRs

As per discussion: https://github.com/rich-iannone/pointblank/discussions/302#discussioncomment-485990

### CODE REVIEW

**Comment by rich-iannone** [comment]
Thank you so much for all of this effort! I didn't encounter the same building problems you did so everything ran smoothly with what you provided. I updated some of the documentation that refers to the available languages.

Here are some screenshots of how various reports look in Danish:

table_scan_da

agent_report_da

agent_email_da

**Comment by rich-iannone** [comment]
When the CI checks all pass, I'll merge this pull request.

**Review by rich-iannone — APPROVED** [review]
LGTM

**Comment by LDalby** [comment]
Looks great! 
I'd be surprised if there weren't some of my translations that needs to be sharpened, but as I get to see them in context I will probably be able to come up with a better version. 
I'll try to collect changes as I go along and open a new PR when I've collected a few.

**Pull request merged**
