### PR TITLE
Simplify dplyr code

### PR DESCRIPTION
**Pull request by olivroy**
# Summary

Potentially seeking performance improvements.

### CODE REVIEW

**Comment by rich-iannone** [comment]
This is great @olivroy ! We will review shortly. And if you're interested, please add yourself as a contributor in DESCRIPTION.

**Review by yjunechoe — DISMISSED** [review]
Thanks! Refactoring just the code we know will directly improve performance is a very nice problem scope. LGTM!

**Review by rich-iannone — DISMISSED** [review]
This is great!

**Comment by rich-iannone** [comment]
@olivroy we've both accepted the PR but, again, feel free to add yourself to the author list (we can merge after that).

**Comment by olivroy** [comment]
Thanks!

**Review by rich-iannone — APPROVED** [review]

**Pull request merged**
