### PR TITLE
Use testthat 3 + remove deprecated features

### PR DESCRIPTION
**Pull request by olivroy**
# Summary

Turns out this was much more work than I imagined

* [Convert to testthat 3](https://testthat.r-lib.org/articles/third-edition.html)
  * Get rid of `expect_equivalent()` (various solutions were needed here, such as creating `expect_equal_unlist()` that is equivalent to `expect_equal(unlist(object), expected)`, use `ignore_attr`
  * Use a snapshot test to capture many warnings
  * Change order of operations to account for [breaking change in testthat 3.1](https://www.tidyverse.org/blog/2021/10/testthat-3-1/#breaking-changes)
  * Use `expect_s3_class()` and `expect_type()` instead of `expect_is()`
* Use `tidyselect::all_of()` instead of superseded `one_of()`
* Get rid of a partial match issue
* Use parallel tests
* Use `expect_no_*()` instead of `expect_*(regexp = NA)`
* Use `testthat::test_path()` to facilitate running tests interactively.
* Avoid dplyr superseded function
* Remove rlang deprecation warning

Also a reminder that to unlock the coverage action, you will have to [add a **Codecov token**](https://github.com/r-lib/actions/issues/834)

Other minor cleanup 

# Checklist

- [x] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html).
- [ ] I have listed any major changes in the [NEWS](https://github.com/rstudio/pointblank/blob/main/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/rstudio/pointblank/tree/main/tests/testthat) for any new functionality.

### CODE REVIEW

**Comment by olivroy** [comment]
@rich-iannone sorry for the many follow-up commits. Now ready for review!

**Comment by rich-iannone** [comment]
This is great @olivroy ! Thanks so much for taking the time for all these fixes :)

@yjunechoe I also invited you to take a look at the changes if you're up for it.

**Review by rich-iannone — DISMISSED** [review]
LGTM and thanks so much!

**Review by yjunechoe — APPROVED** [review]
Wonderful! The deprecation warnings were a headache to track down, so I'm very happy to see them resolved

All tests continue to pass when I test on my end, so LGTM as well!

**Comment by rich-iannone** [comment]
@olivroy it seems like the empty commit trick didn't fix the hanging check of the branch status. Maybe we wait another day for this to (hopefully) update?

**Review by rich-iannone — APPROVED** [review]

**Comment by olivroy** [comment]
I don't know what happened. I tried to push a commit, but reverted it and force pushed. And then it is hanging. But the branch is the same as when you reviewed it..

Can you merge anyway? I don't think this will fix itself


Like I did

```r
gert::git_reset_hard("HEAD~1")
gert::git_push(force = TRUE)
```

and github didn't like this.

**Comment by rich-iannone** [comment]
I don't have a way through the GitHub UI. And I tried through GH Mobile but it's the same hanging state. I might work itself out in time. Worst case scenario is you make another PR with the same changes.

**Comment by rich-iannone** [comment]
That worked!

**Comment by rich-iannone** [comment]
Alright! After CI runs, I'll merge!

**Comment by olivroy** [comment]
I just did

```r
gert::git_reset_soft("HEAD~3")
gert::git_commit_all("commit to unstale branch")
gert::git_push(force = TRUE)
```

and it worked! guess GitHub didn't like removing a commit, but doesn't mind combining into many. The commits are less informative now, but it is fine since you both reviewed it already!)

**Comment by rich-iannone** [comment]
Thanks again @olivroy for modernizing the codebase. I will add a CodeCov token soon!

**Pull request merged**
