### PR TITLE
Debugging codecov

### PR DESCRIPTION
**Pull request by yjunechoe**
Trying to debug codecov GHA failure by hitting it directly in this PR.

### CODE REVIEW

**Comment by yjunechoe** [comment]
🤦I introduced the fails because `test-draft_validation.R` skips on windows (which I use) - since I haven't been updating the snaps, the GHA has been running snapshot tests against outdated snaps and failing this whole time (because `draft_validation()` now writes `c()` instead of `vars()`).

@rich-iannone I also edited the codecov workflow file to include a "show testthat output" step, which could be useful for future debugging. Can I merge this in as well?

**Comment by rich-iannone** [comment]
Showing the testthat output is great. Thank you for solving this!

**Review by rich-iannone — APPROVED** [review]
lgtm

**Comment by rich-iannone** [comment]
(Go ahead and merge this yourself.)

**Pull request merged**
