### PR TITLE
Correct error in function name for get_html_summary()

### PR DESCRIPTION
**Pull request by ekothe**
Fixes error where README.md incorrectly referred to html_summary() rather than get_html_summary() as the method for creating an HTML interrogation report.

### CODE REVIEW

**Comment by rich-iannone** [comment]
@ekothe this is great, thanks for submitting this PR! The scope of the PR seems to include some work-in-progress stuff for the `col_vals_in_set()` function. I’m not sure if that was intended but it’s fine to keep adding commits to fix that. 

Also, could you make the README change to the .Rmd version and then knit? (The .md version is the processed output of the pair.)

Thanks again!

**Comment by ekothe** [comment]
Whoops! Sorry, didn't realise I was doing my WIP on col_vals_in_set() on the same branch. I'll roll back those changes (since they are not working anyway) and make changes to the .RMD

**Comment by ekothe** [comment]
@rich-iannone the most recent commit should resolve the documentation issue without including the WIP for col_values_in_set.

**Comment by rich-iannone** [comment]
@ekothe This is great, really appreciate!

**Pull request merged**
