### PR TITLE
fix grammatical error in vignette

### PR DESCRIPTION
**Pull request by DavZim**
`EVAL` lets us know whether there would **be** issues

### CODE REVIEW

**Comment by rich-iannone** [comment]
Thank you very much for this PR!

**Comment by DavZim** [comment]
Always a pleasure, especially if its this simple :)
BTW, awesome package, thank you for providing it!

**Comment by rich-iannone** [comment]
This is a strange place to ask but, if you have the interest and time, could you check whether my German translations are reasonable? They live in `https://github.com/rich-iannone/pointblank/blob/master/R/utils_text.R` and in `https://github.com/rich-iannone/pointblank/blob/master/R/utils_text_table_scan.R`. For a time I worked in Germany (i.e., had good German language skills) but that was a *long* time ago.

**Comment by DavZim** [comment]
Not a strange place to ask, if you ask me...
Sure, I can do that. I will send a PR later today or tomorrow.

**Comment by DavZim** [comment]
Quick question, do you have an example that uses most of the translations of https://github.com/DavZim/pointblank/blob/master/R/utils_text.R?

**Comment by DavZim** [comment]
Also: do you want to allow the console logs (i.e., `ℹ Step 2: an evaluation issue requires attention (ERROR).` in https://github.com/rich-iannone/pointblank/blob/487ab0e76eeff14477e8c3dd13ce67f3aa855c04/R/interrogate.R) to be in different languages?

**Comment by rich-iannone** [comment]
I apologize for the delay in getting back to you (had to fix some pretty bad bugs in master that was preventing the report from displaying reliably without error). 

For an example that gets at least some of the translations visible, there is this:

```r
library(pointblank)
library(tidyverse)

al <- action_levels(warn_at = 0.1, stop_at = 0.2)

agent <-
  create_agent(tbl = small_table, actions = al, reporting_lang = "de") %>%
  col_vals_gt(vars(g), 100, preconditions = ~ . %>% dplyr::mutate(g = a + 95)) %>%
  col_vals_lt(vars(c), vars(d), preconditions = ~ . %>% dplyr::mutate(d = d - 200)) %>%
  col_vals_in_set(vars(f), c("low", "mid", "high", "higher")) %>%
  col_vals_not_in_set(vars(f), LETTERS[1:8]) %>%
  col_vals_between(vars(c), 0, 10) %>%
  col_vals_not_between(vars(c), 100, 500) %>%
  col_vals_regex(vars(b), ".-...-...") %>%
  col_vals_not_null(vars(a)) %>%
  col_is_date(vars(date)) %>%
  rows_distinct(columns = vars(a, b, c, d, e, f)) %>%
  rows_distinct() %>%
  conjointly(
    ~ col_vals_in_set(., vars(f), c("low", "mid", "high", "higher")),
    ~ col_vals_not_in_set(., vars(f), LETTERS[1:8]),
    ~ col_vals_between(., vars(c), 0, 10)
  )
```

Also, I do think the console logs should be translated. Thank you for reminding me of that!

I'm going to open a new GH issue to further this discussion, and I'll bring a summary of these discussions to that issue.

Thanks!

**Comment by rich-iannone** [comment]
@DavZim I opened the new issue: https://github.com/rich-iannone/pointblank/issues/115

**Pull request merged**
