### PR TITLE
tidyselect integration in `has_columns()`

### PR DESCRIPTION
**Pull request by yjunechoe**
This PR integrates `{tidyselect}` for `has_columns()`. Namely, `{tidyselect}` *helpers* can now be used. These return `FALSE` if no columns are found:

```r
small_table %>% has_columns(starts_with("z"))
#> [1] FALSE
```

This also straightforwardly deprecates `vars()` with `c()` (though `vars()` still works):

```r
small_table %>% has_columns(vars(a, b))
#> [1] TRUE
small_table %>% has_columns(c(a, b))
#> [1] TRUE
```

But this also introduces one point of friction - how should `c(a, starts_with("z"))` be evaluated? We can't rely on "zero match" or "selection failure" - for example, `dplyr::select()` is happy about this query:

```r
small_table %>% dplyr::select(c(a, starts_with("z"))) %>% print(n=1)
#> # A tibble: 13 × 1
#>       a
#>   <int>
#> 1     2
#> # ℹ 12 more rows
```

The reasoning I've arrived at in this PR is:
1) When users explicitly specify `starts_with("z")` as part of `columns`, they probably expect a match for that, therefore
2) `c(a, starts_with("z"))` should be FALSE because `starts_with("z")` by itself returns FALSE, therefore
3) `has_columns(c(a, starts_with("z")))` should be equivalent to `has_columns(a) & has_columns(starts_with("z"))`

This is backwards compatible because `has_columns(vars(a, b))` is also `has_columns(vars(a)) & has_columns(vars(b))`.

In sum, the slight change in `has_columns()`'s implementation (beyond support for tidyselect helpers) is that it calls `eval_select()` on *each individual element* of `c()`/`vars()`, and then reduces with `all()`. But this shouldn't really impact performance in the grand scheme of things.

Related: #497

---

I'm going to move onto writing tests - if any somewhat complex yet plausible examples of `has_columns()` comes to mind, please let me know!

### CODE REVIEW

**Comment by yjunechoe** [comment]
This was pretty straightforward given the infrastructure we already set up for tidyselect! Now onto `info_columns()`, which should be the last `columns` to move to tidyselect

**Review by rich-iannone — APPROVED** [review]
LGTM!

**Comment by rich-iannone** [comment]
This is great! Thank you for taking on all of these tidyselect modernization tasks. Everything to do with column selection feels really cohesive now and complete!

**Comment by yjunechoe** [comment]
Of course -- it's a lot of fun!

**Pull request merged**
