### PR TITLE
initial work to make DATA_TYPE query work with PostgreSQL databases

### PR DESCRIPTION
**Pull request by pachadotdev**

### CODE REVIEW

**Review by rich-iannone — APPROVED** [review]
Looks great!

**Review by rich-iannone — APPROVED** [review]

**Comment by pachadotdev** [comment]
@rich-iannone I can't merge

**Comment by rich-iannone** [comment]
I’ll change your access, sorry about that.

**Comment by pachadotdev** [comment]
easy

**Pull request merged**
